"""Live2D-style layer source: the fox in a front "puppet" pose as static, separated meshes.

build.py --layers writes
  web/public/models/fox_layers.glb  one static mesh per 2D layer (same material names)
  web/public/live2d/rig.json        pivots / chains of the pose in 2D (x, y) = Blender (x, z)
The web layer renderer (web/scripts/render_layers.mjs) turns the meshes into PNG/WebP layers.
"""
from __future__ import annotations

import json

import numpy as np

from . import config as C
from . import model
from .assemble import Part
from .poses import Pose, Rig, Skin

OUT_GLB = C.ROOT / "web" / "public" / "models" / "fox_layers.glb"
OUT_RIG = C.ROOT / "web" / "public" / "live2d" / "rig.json"

# Back-to-front draw order of the 2D puppet.
ORDER = ["Tail", "Leg_L", "Leg_R", "Body", "Arm_L", "Arm_R", "ScarfFlap", "Scarf",
         "Ear_L", "Ear_R", "Head", "Nose", "Eye_L", "Eye_R", "EyeHappy_L", "EyeHappy_R",
         "EyeSleep_L", "EyeSleep_R", "Brow_L", "Brow_R", "MouthSmile", "MouthOpen"]


def puppet_pose(rig) -> Pose:
    """Front-facing rest pose = the 3D idle stance (arms relaxed at the sides, collision-free,
    fingers folded into mittens); head, ears, tail at rest."""
    from .clips import Lib
    p = Lib(rig).stand()
    for b in ("ear_L", "ear_R"):
        p.rot.pop(b, None)
    return p


def _sub(part: Part, face_mask, name):
    """Sub-mesh with the faces in face_mask (vertices re-indexed)."""
    F = np.asarray(part.faces)[face_mask]
    used = np.unique(F)
    remap = -np.ones(len(part.verts), dtype=np.int64)
    remap[used] = np.arange(len(used))
    sel = lambda a: None if a is None else np.asarray(a)[used]  # noqa: E731
    return Part(name, np.asarray(part.verts)[used], remap[F], material=part.material,
                materials=part.materials,
                material_ids=None if part.material_ids is None else np.asarray(part.material_ids)[face_mask],
                normals=sel(part.normals), colors=sel(part.colors), ao=sel(part.ao), uv=sel(part.uv),
                weights={k: np.asarray(v)[used] for k, v in part.weights.items()})


def split_head(head: Part):
    """Head -> Head (core) + Ear_L + Ear_R, with an overlap band so no seam shows."""
    F = np.asarray(head.faces)
    out = []
    ear_any = np.zeros(len(F))
    for s in ("L", "R"):
        w = np.asarray(head.weights.get(f"ear_{s}", 0)) + np.asarray(head.weights.get(f"earTip_{s}", 0))
        wf = w[F].mean(1)
        ear_any = np.maximum(ear_any, wf)
        out.append(_sub(head, wf > 0.2, f"Ear_{s}"))
    out.insert(0, _sub(head, ear_any < 0.8, "Head"))
    return out


def build_layer_parts():
    rig = Rig(model.bone_table())
    pose = puppet_pose(rig)
    parts = []
    for p in model.build_parts():
        pieces = split_head(p) if p.name == "Head" else [p]
        for q in pieces:
            sk = Skin(rig, [q])
            V = sk.deform(pose)
            N = sk.deform_normals(pose, np.asarray(q.normals)) if q.normals is not None else None
            parts.append(Part(q.name, V, q.faces, material=q.material, materials=q.materials,
                              material_ids=q.material_ids, normals=N, colors=q.colors, ao=q.ao, uv=q.uv))
    names = {p.name for p in parts}
    missing = [n for n in ORDER if n not in names]
    assert not missing, missing
    return parts, rig, pose


def rig_json(rig: Rig, pose: Pose):
    """Pivots in 2D (x, y) = Blender (x, z) for the posed skeleton + chains for bending."""
    Qw, Hw = rig.fk(pose)
    tail = lambda b: rig.tail_world(Qw, Hw, b)  # noqa: E731
    xy = lambda v: [round(float(v[0]), 5), round(float(v[2]), 5)]  # noqa: E731
    piv = {b: xy(Hw[b]) for b in rig.order}
    for b in rig.order:
        piv[b + ".tail"] = xy(tail(b))
    chains = {
        "tail": [f"tail_{i}" for i in range(1, 7)],
        "arm_L": ["upperArm_L", "forearm_L", "paw_L"],
        "arm_R": ["upperArm_R", "forearm_R", "paw_R"],
        "ear_L": ["ear_L", "earTip_L"],
        "ear_R": ["ear_R", "earTip_R"],
        "flap": ["scarfFlap_1", "scarfFlap_2"],
        "leg_L": ["thigh_L", "shin_L", "foot_L"],
        "leg_R": ["thigh_R", "shin_R", "foot_R"],
    }
    return {
        "_comment": "2D coordinates in model units: x = fox's left (+), y = up. Generated by tools/fox_build/layers.py",
        "order": ORDER,
        "pivots": piv,
        "chains": {k: [piv[b] for b in v] + [piv[v[-1] + ".tail"]] for k, v in chains.items()},
        "head_center": [C.P["head_center"][0], C.P["head_center"][2]],
        "eye_size": list(C.P["eye_size"]),
    }


def build(bpy):
    from .assemble import get_material
    parts, rig, pose = build_layer_parts()
    col = bpy.context.scene.collection
    for p in parts:
        V = np.asarray(p.verts, np.float32); F = np.asarray(p.faces, np.int32)
        me = bpy.data.meshes.new(p.name)
        me.vertices.add(len(V)); me.vertices.foreach_set("co", V.ravel())
        me.loops.add(len(F) * 3); me.loops.foreach_set("vertex_index", F.ravel())
        me.polygons.add(len(F))
        me.polygons.foreach_set("loop_start", (np.arange(len(F)) * 3).astype(np.int32))
        me.polygons.foreach_set("loop_total", np.full(len(F), 3, np.int32))
        me.update(calc_edges=True)
        me.polygons.foreach_set("use_smooth", np.ones(len(F), bool))
        if p.colors is not None:
            c = np.asarray(p.colors, np.float32)
            c = np.hstack([c, np.ones((len(c), 1), np.float32)]) if c.shape[1] == 3 else c
            a = me.color_attributes.new("Col", "FLOAT_COLOR", "POINT")
            a.data.foreach_set("color", c.ravel())
            me.color_attributes.active_color = a
        if p.ao is not None:
            me.attributes.new("_AO", "FLOAT", "POINT").data.foreach_set("value", np.asarray(p.ao, np.float32))
        if p.uv is not None:
            uvl = me.uv_layers.new(name="UVMap")
            uvl.data.foreach_set("uv", np.asarray(p.uv, np.float32)[F.ravel()].ravel())
        for m in (p.materials or [p.material]):
            me.materials.append(get_material(bpy, m))
        if p.material_ids is not None:
            me.polygons.foreach_set("material_index", np.asarray(p.material_ids, np.int32))
        if p.normals is not None:
            me.normals_split_custom_set_from_vertices([tuple(n) for n in p.normals])
        col.objects.link(bpy.data.objects.new(p.name, me))
    OUT_RIG.parent.mkdir(parents=True, exist_ok=True)
    OUT_RIG.write_text(json.dumps(rig_json(rig, pose), indent=1), encoding="utf-8")
    return OUT_GLB
